### ISSUE TITLE
How to get the PTT data

### ISSUE THREAD

**Issue by playma** [f496328mm/Crawler_and_Share#2]
The URL below does not work.
http://114.34.138.146/phpmyadmin/

How can I get the PTT data you crawled?
Thank you so much.

**Comment by f496328mm** [comment]
sorry，ip was be changed to 114.32.60.100.
you can get data by R or python.
R : https://github.com/f496328mm/Crawler_and_Share/blob/master/load_data_from_mysql.r
Python : https://github.com/f496328mm/Crawler_and_Share/blob/master/LoadPttData.py
